name: Page cleaner

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:

concurrency:
  # group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  group: clean-unused-files-from-github-pages
  cancel-in-progress: true

jobs:
  cleaner:
    runs-on: ubuntu-latest
    permissions: read-all
    timeout-minutes: 120
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      node_version: 18.x
      YARN_CHECKSUM_BEHAVIOR: update

    steps:
      - run: git config --global core.autocrlf false
      - uses: szenius/set-timezone@v1.2
        name: set os timezone
        with:
          timezoneLinux: 'Asia/Jakarta'
          timezoneMacos: 'Asia/Jakarta'
          timezoneWindows: 'Indonesia Standard Time'
      - run: git config --global  core.ignorecase false
      - uses: actions/checkout@v3
        name: checkout master
        with:
          ref: master
          repository: dimaslanjaka/page
          token: '${{ secrets.ACCESS_TOKEN }}'
          submodules: recursive
      - uses: actions/checkout@v3
        name: checkout gh-pages
        with:
          ref: gh-pages
          path: page
          repository: dimaslanjaka/page
          token: '${{ secrets.ACCESS_TOKEN }}'
      - uses: actions/cache@v3
        id: cache
        name: init cache
        with:
          path: |
            ./tmp
            ./node_modules
            ./packages/safelinkify/node_modules
            **/.yarn
          key: ${{ runner.os }}-${{ env.node_version }}
          restore-keys: |
            ${{ runner.os }}-${{ env.node_version }}
            ${{ runner.os }}-
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: yarn install
      - run: gulp page:clean
      - run: |
          git config --global user.name 'dimaslanjaka'
          git config --global user.email 'dimaslanjaka@gmail.com'
          git add .
          git config core.eol lf
          git config core.autocrlf input
          git checkout-index --force --all
          if [ $(git status --porcelain | wc -l) -gt "0" ]; then
            git commit -m "chore: clean unused files"
          fi
          git pull -X theirs
          if [ $(git diff --cached --numstat | wc -l) -gt "0" ]; then
            git push
          fi
        name: commit pages
        working-directory: page
